django_comparison_dashboard/urls.py
from django.urls import path

from . import forms, views

app_name = "django_comparison_dashboard"

urlpatterns = [
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("scalars/", views.ScalarView.as_view(), name="render_data"),
    path("scalars/chart/", views.ScalarView.as_view(embedded=True), name="data_chart"),
    path("scenarios/", views.ScenarioSelectionView.as_view(), name="scenarios"),
    path("scenario_detail/", views.ScenarioDetailView.as_view(), name="scenario_detail"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("scenario_form/", views.ScenarioFormView.as_view(), name="scenario_form"),
    path("add_label/", views.KeyValueFormPartialView.as_view(prefix="labels", form=forms.LabelForm), name="add_label"),
    path("remove_label/",views.KeyValueFormPartialView.as_view(prefix="labels", form=forms.LabelForm),
        name="remove_label"),
    path("add_color/", views.KeyValueFormPartialView.as_view(prefix="colors", form=forms.ColorForm), name="add_color"),
    path("remove_color/",views.KeyValueFormPartialView.as_view(prefix="colors", form=forms.ColorForm),
         name="remove_color"),
    path("save/", views.save_filter_settings, name="save"),
    path("save/name", views.save_precheck_name, name="save_name"),
    path("load/", views.load_filter_settings, name="load"),
    path("change_chart_type/", views.change_chart_type, name="change_chart_type"),
]

django_comparison_dashboard/templates/django_comparison_dashboard/button.html
{% extends 'django_comparison_dashboard/base.html' %}

{% block content %}

<div>
    <p>Welcome!</p>

    <button hx-trigger="click" hx-get="{% url 'django_comparison_dashboard:magic' %}" hx-target='#show-sth' hx-swap="innerHTML">
        Click me!
    </button>
</div>

<div id="show-sth">
    <p>Wait for it</p>
</div>

{% endblock content %}

django_comparison_dashboard/templates/django_comparison_dashboard/dashboard.html
{% extends "base.html" %}

{% load static %}
{% load partials %}

{% block content %}
  <div class="container diagrams">
    <!-- Scenario Selection Forms -->
    <!-- Content with Filter / Presentation Tab and Charts -->
    <h1 class="d-flex align-items-center">
      <svg width="32" height="32" viewBox="0 0 134 134" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="67" cy="67" r="66" fill="#D7ECFA"/>
        <line x1="39" y1="106" x2="39" y2="95" stroke="black" stroke-width="8"/>
        <line x1="39" y1="87" x2="39" y2="69" stroke="black" stroke-width="8"/>
        <line x1="63" y1="106" x2="63" y2="82" stroke="black" stroke-width="8"/>
        <line x1="63" y1="73" x2="63" y2="51" stroke="black" stroke-width="8"/>
        <line x1="87" y1="106" x2="87" y2="69" stroke="black" stroke-width="8"/>
        <line x1="87" y1="60" x2="87" y2="26" stroke="black" stroke-width="8"/>
      </svg>
      <span class="ms-3">
        Model Results
      </span>
    </h1>
    <div class="diagrams__content">
      <div class="diagrams__filters">
        <!-- Load Filter Settings -->
        {% startpartial load_settings inline=True %}
        <div class="diagrams__settings">
          <form method="get"
            action="{% url 'django_comparison_dashboard:load' %}"
            class="d-flex">
            <select class="form-control flex-grow-1"
                    id="load_name"
                    name="name"
                    label="name">
              {% for name in name_list %}<option value="{{ name.name }}">{{ name.name }}</option>{% endfor %}
            </select>
            {% for scenario in scenarios %}<input type="hidden" name="scenario_id" value="{{ scenario }}" />{% endfor %}
            <input type="submit"
                  class="btn button button--secondary ms-2"
                  value="Load Filter Settings" />
          </form>
        </div>
      {% endpartial %}
      <!-- contains Filters in different Tabs -->
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active"
                 id="filters-tab"
                 data-bs-toggle="tab"
                 href="#filters">Scenario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 id="o-a-l-tab"
                 data-bs-toggle="tab"
                 href="#o_a_label">Other</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 id="graph-options-tab"
                 data-bs-toggle="tab"
                 href="#graph_options_tab">Graph</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 id="display-options-tab"
                 data-bs-toggle="tab"
                 href="#display_options_tab">Display</a>
            </li>
          </ul>
        </div>
        <div class="card-body" hx-ext="multi-swap">
          <div class="tab-content">
            <div class="tab-pane active" id="filters" role="tabpanel">
              <!-- General Filter Selection -->
              <h5 class="card-title">General Filters</h5>
              {% startpartial filters inline=True %}
              {% for scenario in scenarios %}<input type="hidden" name="scenario_id" value="{{ scenario }}" />{% endfor %}
              {{ scenario_filter.form.as_p }}
            {% endpartial %}
          </div>
          <div class="tab-pane" id="o_a_label" role="tabpanel">
            <!-- Order/Aggregation- and Unit Settings -->
            <h5 class="card-title">Order, Aggregation and Label Settings</h5>
            {{ order_aggregation_form.as_p }}
            <hr />
            {{ unit_form.as_p }}
            <hr />
            <div id="labels" class="pb-3">{{ label_form.as_p }}</div>
            <button type="button"
                    class="btn button button--secondary"
                    hx-post="{% url 'django_comparison_dashboard:add_label' %}"
                    hx-include="#labels"
                    hx-target="#labels">Add label</button>
            <button class="close btn button button--link"
                    aria-label="Remove label"
                    hx-post="{% url 'django_comparison_dashboard:remove_label' %}"
                    hx-include="#labels"
                    hx-target="#labels">Remove label</button>
          </div>
          {% startpartial graph_options inline=True %}
          <div class="tab-pane" id="graph_options_tab" role="tabpanel">
            <!-- General Graph Options -->
            <h5 class="card-title">General Graph Options</h5>
            <form hx-post="{% url 'django_comparison_dashboard:change_chart_type' %}"
                  hx-swap="multi:#graph_options_tab,#display_options_tab"
                  hx-trigger="change">
              {{ chart_type_form.as_p }}
            </form>
            {{ graph_options_form.as_p }}
            <hr />
            <div id="colors" class="pb-3">{{ color_form.as_p }}</div>
            <button type="button"
                    class="btn button button--secondary"
                    hx-post="{% url 'django_comparison_dashboard:add_color' %}"
                    hx-include="#colors"
                    hx-target="#colors">Add color</button>
            <button class="close btn button button--link"
                    aria-label="Remove color"
                    hx-post="{% url 'django_comparison_dashboard:remove_color' %}"
                    hx-include="#colors"
                    hx-target="#colors">Remove color</button>
          </div>
        {% endpartial %}
        {% startpartial display_options inline=True %}
        <div class="tab-pane" id="display_options_tab" role="tabpanel">
          <!-- Display Options -->
          <h5 class="card-title">Display Options</h5>
          {{ display_options_form.as_p }}
        </div>
      {% endpartial %}
    </div>
  </div>
</div>
<!-- Save Filter Settings -->
  <div class="diagrams__save">
    <form method="post"
      id="save_settings"
      hx-swap="innerhtml"
      hx-post="{% url 'django_comparison_dashboard:save' %}"
      hx-include="#filters, #o_a_label, #graph_options_tab, #display_options_tab"
      hx-target="#save_error"
      novalidate
      _="on load hide .alert">
    <div hx-ext='response-targets' class="d-flex">
      <input type="text"
        class="form-control"
        id="save_name"
        name="name"
        label="name"
        hx-swap="innerhtml"
        hx-trigger="keyup delay:500ms changed"
        hx-post="{% url 'django_comparison_dashboard:save_name' %}"
        hx-target="#save_sucess"
        {# djlint:off #} hx-target-4*="#save_error" {# djlint:on #}
        _="on htmx:afterRequest if event.detail.xhr.status === 200 show #save_sucess hide #save_error remove @disabled from #save_button else show #save_error hide #save_sucess add @disabled to #save_button" />
        <button type="submit" id="save_button" class="btn button button--secondary ms-2" disabled>Save Filter Settings</button>
        <div id="save_error" class="alert alert-warning"></div>
        <div id="save_sucess" class="alert alert-success"></div>
      </div>
    </form>
  </div>
</div>
<!-- contains Charts and Table with Tabbed Interface -->
<div class="diagrams__graph">
  <div class="d-flex">
    <button type="button"
            class="btn button button--primary"
            hx-ext="multi-swap"
            hx-get="{% url 'django_comparison_dashboard:render_data' %}"
            hx-include="#scenario_id, #filters, #o_a_label, #graph_options_tab, #display_options_tab"
            hx-swap="multi:#table,#plot">
      <svg width="16" height="13" viewBox="0 0 16 13" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M1 12L6 4.5L10 8.5L15 0.5" stroke="white"/>
      </svg>
      <span class="ms-2">
        Render chart and table
      </span>
    </button>
    <button id="download-button" class="btn button button--secondary ms-2"
            hx-get="{% url 'django_comparison_dashboard:render_data' %}?download=true"
            hx-trigger="click"
            hx-include="#scenario_id, #filters, #o_a_label, #graph_options_tab, #display_options_tab"
            hx-swap="none"
            hx-boost="true">
      <span class="ms-2">Download Data</span>
    </button>
  </div>
  <div class="card mt-3"
    {# djlint:off #}
       style="margin-top: 0"
    {# djlint:on #}>
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs"
          id="chartTableTab"
          role="tablist">
        <li class="nav-item">
          <a class="nav-link active"
            id="plot-tab"
            data-bs-toggle="tab"
            href="#plot"
            role="tab">
            <svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
              <line x1="1.5" y1="6" x2="1.5" y2="16" stroke="currentColor"/>
              <line x1="13.5" y1="3" x2="13.5" y2="16" stroke="currentColor"/>
              <line x1="5.5" y1="-9.56187e-09" x2="5.5" y2="16" stroke="currentColor"/>
              <line x1="15" y1="15.5" y2="15.5" stroke="currentColor"/>
              <line x1="9.5" y1="10" x2="9.5" y2="16" stroke="currentColor"/>
            </svg>
            <span class="ms-2">
              Chart
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             id="table-tab"
             data-bs-toggle="tab"
             href="#table"
             role="tab">
             <svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
              <line x1="16" y1="15.5" y2="15.5" stroke="currentColor"/>
              <line x1="16" y1="0.5" y2="0.5" stroke="currentColor"/>
              <line x1="0.5" y1="16" x2="0.5" y2="-5.96244e-09" stroke="currentColor"/>
              <line x1="5.5" y1="16" x2="5.5" y2="-5.96244e-09" stroke="currentColor"/>
              <line x1="15.5" y1="15" x2="15.5" y2="-1" stroke="currentColor"/>
              <line x1="16" y1="5.5" y2="5.5" stroke="currentColor"/>
              <line x1="16" y1="10.5" y2="10.5" stroke="currentColor"/>
            </svg>
             <span class="ms-2">
              Table
             </span>
            </a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="tab-content">
        <div class="tab-pane fade show active" id="plot" role="tabpanel">
          <div id="plot-content"
            class="mb-3"
            {# djlint:off #}
               style="height: calc(100vh - 250px);overflow-y: auto"
            {# djlint:on #}
            ></div>
        </div>
        <div class="tab-pane fade" id="table" role="tabpanel">
          <div id="table-content"
            {# djlint:off #}
               style="max-height: 300px; overflow-y: auto;"
            {# djlint:on #}
            ></div>
          <!-- Added max-height to decrease table size and allow scrolling -->
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
{% endblock content %}
{% block javascript %}
  {{ block.super }}
  <script>
    $(function() {
      $('[data-toggle="tooltip"]').tooltip();
    });
  </script>
  <script src="https://unpkg.com/htmx.org@1.9.12"></script>
  <script src="https://unpkg.com/htmx.org@1.9.12/dist/ext/multi-swap.js"></script>
  <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
  <script src="{% static "vendors/datatables/dataTables.js" %}"></script>
  <script src="{% static "vendors/json-viewer/jquery.json-viewer.js" %}"></script>
  <script src="{% static "js/tables.js" %}"></script>
{% endblock javascript %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "vendors/datatables/dataTables.css" %}" />
  <link rel="stylesheet" href="{% static "vendors/json-viewer/jquery.json-viewer.css" %}" />
  <style>
    .card-header {
      padding: 0.5rem;
      /* Reduce padding of the card header */
    }

    .tab-pane {
      font-size: 1rem;
    }

    .tab-content {
      font-size: 1rem;
    }
  </style>
{% endblock css %}
{% block inline_javascript %}
  <script>
    window.addEventListener('DOMContentLoaded', () => {
      $('.ui.dropdown').dropdown();
      $('.ui.dropdown.clearable').dropdown({
        "clearable": true
      });
    });
  </script>
  <script>
    document.body.addEventListener('htmx:afterRequest', function(evt) {
      if (evt.detail.target.id === 'download-button' && evt.detail.xhr.status === 200) {
        const contentDisposition = evt.detail.xhr.getResponseHeader('Content-Disposition');
        if (contentDisposition && contentDisposition.indexOf('attachment') !== -1) {
          // Create a temporary link to trigger the download
          const url = URL.createObjectURL(new Blob([evt.detail.xhr.response], { type: 'text/csv' }));
          const link = document.createElement('a');
          link.href = url;
          link.download = 'table_result_data.csv';
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          URL.revokeObjectURL(url);
        }
      }
    });
  </script>
{% endblock inline_javascript %}

django_comparison_dashboard/templates/django_comparison_dashboard/scenario_list.html
{% extends "base.html" %}

{% load partials %}

{% block content %}
  <form hx-get="{% url 'django_comparison_dashboard:scenario_detail' %}"
        hx-target="#selected_scenarios"
        hx-swap="afterbegin">
    {% csrf_token %}
    <select hx-get="{% url 'django_comparison_dashboard:scenarios' %}"
            hx-target="#scenarios"
            hx-trigger="change"
            hx-swap="innerHTML"
            name="source">
      {% for source in sources %}<option value="{{ source.id }}">{{ source.name }}</option>{% endfor %}
    </select>
    <div id="scenarios">
      {% startpartial scenarios inline=True %}
      {% if scenarios %}
        <select name="scenario">
          {% for scenario in scenarios %}<option value="{{ scenario.id }}">{{ scenario.name }}</option>{% endfor %}
        </select>
      {% endif %}
    {% endpartial %}
  </div>
  <button type="submit">Add scenario</button>
</form>
<div>
  Selected scenarios:
  <form method="get"
        action="{% url 'django_comparison_dashboard:dashboard' %}">
    {% csrf_token %}
    <ul id="selected_scenarios">
      {% startpartial scenario inline=True %}
      {% if scenario %}
        <li>
          <input name="scenario_id" value="{{ scenario.id }}" hidden />
          #{{ scenario.id }}: {{ scenario.name }}
        </li>
      {% endif %}
    {% endpartial %}
  </ul>
  <button type="submit">Select scenarios</button>
</form>
</div>
{% endblock content %}
{% block javascript %}
  {{ block.super }}
  <script src="https://unpkg.com/htmx.org@1.6.0"></script>
{% endblock javascript %}

django_comparison_dashboard/templates/django_comparison_dashboard/upload_data.html
{% extends "base.html" %}

{% load partials %}

{% block content %}
  <form hx-get="{% url 'django_comparison_dashboard:scenario_form' %}"
        hx-target="#scenario"
        hx-trigger="change">
    <label for="source">Select source:</label>
    <select id="source" name="source">
      {% for source in sources %}<option value="{{ source }}">{{ source }}</option>{% endfor %}
    </select>
  </form>
  <div id="scenario">
    {% startpartial scenario inline=True %}
    {% if form %}
      <form method="post"
            hx-post="{% url 'django_comparison_dashboard:scenario_form' %}"
            hx-target="#scenario"
            hx-include="[name='source']"
            hx-encoding='multipart/form-data'>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
      </form>
    {% endif %}
  {% endpartial %}
</div>
{% endblock content %}
{% block javascript %}
  {{ block.super }}
  <script src="https://unpkg.com/htmx.org@1.6.0"></script>
{% endblock javascript %}