django_comparison_dashboard/urls.py
from django.urls import path

from . import forms, views

app_name = "django_comparison_dashboard"

urlpatterns = [
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("scalars/", views.ScalarView.as_view(), name="render_data"),
    path("scalars/chart/", views.ScalarView.as_view(embedded=True), name="data_chart"),
    path("scenarios/", views.ScenarioSelectionView.as_view(), name="scenarios"),
    path("scenario_detail/", views.ScenarioDetailView.as_view(), name="scenario_detail"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("scenario_form/", views.ScenarioFormView.as_view(), name="scenario_form"),
    path("add_label/", views.KeyValueFormPartialView.as_view(prefix="labels", form=forms.LabelForm), name="add_label"),
    path("remove_label/",views.KeyValueFormPartialView.as_view(prefix="labels", form=forms.LabelForm),
        name="remove_label"),
    path("add_color/", views.KeyValueFormPartialView.as_view(prefix="colors", form=forms.ColorForm), name="add_color"),
    path("remove_color/",views.KeyValueFormPartialView.as_view(prefix="colors", form=forms.ColorForm),
         name="remove_color"),
    path("save/", views.save_filter_settings, name="save"),
    path("save/name", views.save_precheck_name, name="save_name"),
    path("load/", views.load_filter_settings, name="load"),
    path("change_chart_type/", views.change_chart_type, name="change_chart_type"),
]

django_comparison_dashboard/templates/django_comparison_dashboard/partials/error.html
<div id="plot">
  <div class="alert alert-danger">An error occurred!</div>
  <button class="btn button button--primary"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseUrl"
          aria-expanded="false"
          aria-controls="collapseUrl">See detailed information</button>
  <div class="collapse" id="collapseUrl">
    <div class="card card-body">
      Error occurred while processing following URL:
      <pre><code>
        {{ requested_url }}
      </code></pre>
      You can send this URL to Admin, so that error can be investigated.
    </div>
  </div>
</div>
<div id="table"></div>

django_comparison_dashboard/templates/django_comparison_dashboard/partials/plot.html
<div id="plot">
  {{ chart|safe }}
  <div class="d-flex flex-row justify-content-end">
    <button type="button"
      class="btn button button--secondary"
      hx-get="{% url 'django_comparison_dashboard:data_chart' %}"
      hx-include="#scenario_id, #filters, #o_a_label, #graph_options_tab, #display_options_tab">
      Embed Chart
    </button>
  </div>
</div>
<div id="table">{{ table|safe }}</div>